- hosts: all
  remote_user: vagrant
  become: true
  become_user: root
  become_method: sudo

  tasks:


###
### RESTART Elasticsearch
###

  - name: Make sure Elasticsearch is restarted
    service:
       name: "{{ item }}"
       state: restarted
       enabled: True
    with_items:
       - elasticsearch
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"
